version: "3"
services:

  sudoku-frontend:
    build: ./
    image: frontend:latest
    depends_on:
      - sudoku-solver
    volumes:
      - .:/app
      - '/app/node_modules' 
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]

  sudoku-solver:
    build: 
      context: ./server
    image: server:latest
    ports:
      - '5001:5000'
    volumes:
      - ./server/:/app
    # --host=0.0.0.0 makes the server publicly available
    # http://flask.pocoo.org/docs/0.12/quickstart/
    command: [ "sh", "-c", "flask run --host=0.0.0.0" ]
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
